version: '3.7'

services:

  quiz-maker-backend:
    image: registry.gitlab.com/matteodibs/quizmaker/quizmaker_be
    environment:
      POSTGRES_JDBC: ${POSTGRES_JDBC}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - quizmaker_db

  postgres_db:
    image: postgres:15.10
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quizmaker_db

networks:
  quizmaker_db:
    driver: bridge

volumes:
  postgres-data: